import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { enumerateSources, profileFor, sync } from './sync-license-profiles.mjs';
import { validateContract } from './validate-license-data.mjs';

const root = path.resolve(new URL('..', import.meta.url).pathname);
test('enumerates the current manifest catalog at runtime', () => { const result = enumerateSources(); assert.equal(result.records.filter(r => r.kind === 'license').length, result.manifest.licenses); assert.equal(result.records.filter(r => r.kind === 'exception').length, result.manifest.exceptions); });
test('creates pending and deprecated profiles with unknown semantics', () => { const record = { id: 'x', kind: 'license', source: { deprecated: false }, fingerprint: { sourceId: 'spdx-license-list', revision: 'r', contentHash: 'h' } }; assert.equal(profileFor(record).review.status, 'pending'); const pending = profileFor(record); const deprecated = profileFor({ ...record, source: { deprecated: true } }, pending); assert.equal(deprecated.review.status, 'not-recommendable'); assert.equal(deprecated.review.recommendable, false); });
test('migrates every current legacy profile conservatively and keeps it pending', () => {
  const legacy = enumerateSources().records.filter(record => record.source.profile);
  assert.ok(legacy.length > 0);
  for (const record of legacy) {
    const profile = profileFor(record);
    assert.equal(profile.review.status, 'pending');
    assert.equal(profile.review.recommendable, false);
    assert.equal(profile.review.evidenceLevel, 'unknown');
    assert.ok(profile.evidence.length >= 3);
    assert.ok(profile.semantic.permissions.some(value => value !== 'unknown') || profile.semantic.obligations.some(value => value !== 'unknown') || profile.semantic.restrictions.some(value => value !== 'unknown'));
    assert.ok(profile.evidence.every(entry => entry.sourceId === 'choose-a-license'));
    for (const field of ['permissions', 'obligations', 'restrictions']) assert.deepEqual(profile.semantic[field], [...new Set(profile.semantic[field])].sort());
    assert.ok(!profile.semantic.permissions.includes('patent-use'));
    assert.ok(!profile.semantic.restrictions.includes('trademark-use'));
    assert.ok(!profile.semantic.obligations.includes('document-changes'));
  }
});
test('migrates an unchanged untouched skeleton but preserves reviewed semantics', () => {
  const record = enumerateSources().records.find(value => value.source.profile);
  const skeleton = profileFor({ ...record, source: { ...record.source, profile: undefined } });
  const migrated = profileFor(record, skeleton);
  assert.ok(migrated.evidence.length > 0);
  const reviewed = { ...migrated, review: { status: 'reviewed', recommendable: true, evidenceLevel: 'strong' } };
  assert.strictEqual(profileFor(record, reviewed), reviewed);
});
test('preserves unchanged reviewed content and stales changed reviewed content', () => { const record = { id: 'x', kind: 'license', source: {}, fingerprint: { sourceId: 'spdx-license-list', revision: 'r', contentHash: 'h' } }; const old = { ...profileFor(record), review: { status: 'reviewed', recommendable: true, evidenceLevel: 'strong' }, evidence: [{ field: 'family', sourceId: 'x', locator: 'x' }] }; assert.strictEqual(profileFor(record, old), old); const changed = profileFor({ ...record, fingerprint: { ...record.fingerprint, contentHash: 'new' } }, old); assert.equal(changed.review.status, 'stale'); assert.equal(changed.review.recommendable, false); assert.deepEqual(changed.semantic, old.semantic); });
test('rejects duplicate or missing source IDs and unsafe IDs', () => { const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'lic003-')); fs.mkdirSync(path.join(temp, 'licenses')); fs.mkdirSync(path.join(temp, 'exceptions')); fs.writeFileSync(path.join(temp, 'manifest.json'), JSON.stringify({ licenses: 1, exceptions: 0 })); fs.writeFileSync(path.join(temp, 'licenses', 'a.json'), JSON.stringify({ type: 'license', id: '../escape' })); assert.throws(() => enumerateSources({ sourceRoot: temp }), /unsafe path segment/); });
test('reports a missing source directory and duplicate IDs', () => { const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'lic003-')); fs.mkdirSync(path.join(temp, 'licenses')); fs.writeFileSync(path.join(temp, 'manifest.json'), JSON.stringify({ licenses: 2, exceptions: 0 })); fs.writeFileSync(path.join(temp, 'licenses', 'a.json'), JSON.stringify({ type: 'license', id: 'same' })); fs.writeFileSync(path.join(temp, 'licenses', 'b.json'), JSON.stringify({ type: 'license', id: 'same' })); assert.throws(() => enumerateSources({ sourceRoot: temp }), /duplicate source ID/); fs.rmSync(path.join(temp, 'licenses', 'b.json')); assert.throws(() => enumerateSources({ sourceRoot: temp }), /missing source directory/); });
test('enumeration performs no network fetch', () => { const original = globalThis.fetch; globalThis.fetch = () => { throw new Error('network access'); }; try { const result = enumerateSources(); assert.equal(result.records.length, result.manifest.licenses + result.manifest.exceptions); } finally { globalThis.fetch = original; } });
test('second write is deterministic and check is read-only', () => { const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'lic003-')); const source = path.join(temp, 'public'); fs.mkdirSync(path.join(source, 'licenses'), { recursive: true }); fs.mkdirSync(path.join(source, 'exceptions')); fs.writeFileSync(path.join(source, 'manifest.json'), JSON.stringify({ licenses: 1, exceptions: 0 })); fs.writeFileSync(path.join(source, 'licenses', 'x.json'), JSON.stringify({ id: 'X', type: 'license', deprecated: false })); const profiles = path.join(temp, 'profiles'); sync({ mode: 'write', sourceRoot: source, profileRoot: profiles }); const before = fs.readFileSync(path.join(profiles, 'licenses', 'id-WA.json'), 'utf8'); sync({ mode: 'write', sourceRoot: source, profileRoot: profiles }); assert.equal(fs.readFileSync(path.join(profiles, 'licenses', 'id-WA.json'), 'utf8'), before); const check = sync({ mode: 'check', sourceRoot: source, profileRoot: profiles }); assert.deepEqual(check.problems, []); });
test('runtime metadata does not alter the canonical source fingerprint', () => { const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'lic003-')); const source = path.join(temp, 'public'); fs.mkdirSync(path.join(source, 'licenses'), { recursive: true }); fs.mkdirSync(path.join(source, 'exceptions')); fs.writeFileSync(path.join(source, 'manifest.json'), JSON.stringify({ licenses: 1, exceptions: 0 })); const file = path.join(source, 'licenses', 'x.json'); fs.writeFileSync(file, JSON.stringify({ id: 'X', type: 'license', deprecated: false })); const before = enumerateSources({ sourceRoot: source }).records[0].fingerprint; fs.writeFileSync(file, JSON.stringify({ id: 'X', type: 'license', deprecated: false, metadata: { review: { status: 'pending' } } })); const after = enumerateSources({ sourceRoot: source }).records[0].fingerprint; assert.deepEqual(after, before); });
test('invalid existing profile fails write without changing it', () => { const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'lic003-')); const source = path.join(temp, 'public'); fs.mkdirSync(path.join(source, 'licenses'), { recursive: true }); fs.mkdirSync(path.join(source, 'exceptions')); fs.writeFileSync(path.join(source, 'manifest.json'), JSON.stringify({ licenses: 1, exceptions: 0 })); fs.writeFileSync(path.join(source, 'licenses', 'x.json'), JSON.stringify({ id: 'X', type: 'license' })); const profiles = path.join(temp, 'profiles'); fs.mkdirSync(path.join(profiles, 'licenses'), { recursive: true }); const invalid = '{"invalid":true}\n'; const target = path.join(profiles, 'licenses', 'id-WA.json'); fs.writeFileSync(target, invalid); assert.throws(() => sync({ mode: 'write', sourceRoot: source, profileRoot: profiles }), /invalid profile/); assert.equal(fs.readFileSync(target, 'utf8'), invalid); });
test('retains an orphan when its source is removed from the snapshot', () => { const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'lic003-')); const source = path.join(temp, 'public'); fs.mkdirSync(path.join(source, 'licenses'), { recursive: true }); fs.mkdirSync(path.join(source, 'exceptions')); const manifest = path.join(source, 'manifest.json'); fs.writeFileSync(manifest, JSON.stringify({ licenses: 1, exceptions: 0 })); const sourceFile = path.join(source, 'licenses', 'x.json'); fs.writeFileSync(sourceFile, JSON.stringify({ id: 'X', type: 'license' })); const profiles = path.join(temp, 'profiles'); sync({ mode: 'write', sourceRoot: source, profileRoot: profiles }); const target = path.join(profiles, 'licenses', 'id-WA.json'); const before = fs.readFileSync(target); fs.rmSync(sourceFile); fs.writeFileSync(manifest, JSON.stringify({ licenses: 0, exceptions: 0 })); assert.throws(() => sync({ mode: 'check', sourceRoot: source, profileRoot: profiles }), /orphan profile \(not deleted/); assert.equal(fs.readFileSync(target).toString(), before.toString()); assert.throws(() => sync({ mode: 'write', sourceRoot: source, profileRoot: profiles }), /orphan profile \(not deleted/); assert.deepEqual(fs.readFileSync(target), before); });
test('records local provenance while unresolved auxiliary sources remain fail-closed', () => { const catalog = enumerateSources(); const locks = JSON.parse(fs.readFileSync(path.join(root, 'data', 'sources.lock.json'), 'utf8')).sources; for (const record of catalog.records) { const profile = profileFor(record); const lock = locks.find(source => source.id === profile.sourceFingerprint.sourceId); assert.ok(lock, `missing source lock for ${record.kind}`); assert.match(profile.sourceFingerprint.revision, /^manifest-sha256:/); assert.equal(lock.revision.status, 'resolved'); assert.equal(lock.contentHash.status, 'resolved'); } assert.ok(locks.some(source => source.revision.status === 'unresolved')); assert.doesNotThrow(() => validateContract({ release: true })); });
